### ISSUE TITLE
Steps to execute the code?

### ISSUE THREAD

**Issue by nishat-sayyed** [317070/kaggle-heart#39]
Can you please provide detailed steps on how to run the code in this repo?
Like the sequence of files to execute and the directories in which the datasets should be stored.
Thank you.

**Comment by IraKorshunova** [comment]
please see the Appendix of this document: [https://github.com/317070/kaggle-heart/blob/master/documentation.pdf](url)

**Comment by nishat-sayyed** [comment]
Thanks
